[package]
name = "lantern"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
sha2 = "0.10"
local-ip-address = "0.5"
reqwest = { version = "0.11", features = ["blocking", "json"] }
ctrlc = "3.4"
